
import type { Article } from './types';

export const mockArticles: Article[] = [
  // --- AI Category ---
  {
    id: 'mock-1',
    title: 'The Unseen Revolution: How Foundational AI Models are Reshaping Industries',
    slug: 'unseen-revolution-foundational-ai-models',
    content: '<p>Foundational models are not just another step in AI; they represent a seismic shift. Unlike narrow AI trained for specific tasks, these massive, pre-trained models like GPT-4 and Claude 3 possess a general understanding of language, logic, and even code. This allows them to be adapted for countless applications with minimal fine-tuning, drastically reducing development time and cost.</p><p>From automating complex legal document analysis to generating novel drug compounds in pharmacology, the impact is broad and deep. We\'re witnessing the "iPhone moment" of AI, where a versatile platform technology unlocks a Cambrian explosion of innovation across sectors previously untouched by artificial intelligence.</p>',
    summary: 'A deep dive into how large-scale, foundational AI models are moving beyond niche applications to become a transformative platform technology, accelerating innovation across every industry.',
    tags: ['AI', 'LLM', 'Transformation'],
    categories: ['AI', 'Tech'],
    company: 'comp-1',
    imageUrl: 'https://picsum.photos/seed/mock-ai-1/600/400',
    imageHint: 'AI abstract network',
    authorId: 'user-1',
    publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    isFeatured: true,
    readTime: 5,
  },
  {
    id: 'mock-2',
    title: 'The Trillion Parameter Race: Who is Leading the LLM Arms Race?',
    slug: 'trillion-parameter-llm-race',
    content: '<p>Google, OpenAI, and Meta are locked in a fierce competition to build the largest and most capable Large Language Models. This "trillion parameter race" is pushing the boundaries of what\'s possible, but it comes at a tremendous computational and environmental cost.</p><p>This article explores the key players, the cutting-edge techniques being used to train these behemoths, and asks the critical question: is bigger always better? We analyze the trade-offs between model size, efficiency, and the emerging focus on smaller, specialized open-source models.</p>',
    summary: 'An inside look at the high-stakes competition between tech giants to build ever-larger language models, exploring the technological and ethical implications of the race to a trillion parameters.',
    tags: ['LLM', 'OpenAI', 'Google', 'Meta'],
    categories: ['AI', 'Big Tech'],
    company: 'comp-2',
    imageUrl: 'https://picsum.photos/seed/mock-ai-2/600/400',
    imageHint: 'glowing data server',
    authorId: 'user-2',
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    isFeatured: true,
    readTime: 6,
  },
  {
    id: 'mock-3',
    title: 'Democratizing AI: The Rise of Open-Source Models and Their Impact',
    slug: 'democratizing-ai-open-source-models',
    content: '<p>While corporate giants dominate headlines, a parallel revolution is happening in the open-source community. Models like Llama 3, Mistral, and Phi-3 are providing powerful alternatives that can be run on consumer hardware, fostering a wave of grassroots innovation.</p><p>This decentralization challenges the dominance of Big Tech, promoting transparency, and allowing developers worldwide to build upon and scrutinize the latest AI advancements. We explore the vibrant ecosystem and its potential to shape a more equitable AI future.</p>',
    summary: 'A look at the growing movement of open-source AI, highlighting key models and platforms that are empowering developers and challenging the dominance of proprietary systems.',
    tags: ['Open Source', 'AI', 'Community'],
    categories: ['AI', 'Startups'],
    company: '',
    imageUrl: 'https://picsum.photos/seed/mock-ai-3/600/400',
    imageHint: 'collaborating developers code',
    authorId: 'user-3',
    publishedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    isFeatured: false,
readTime: 4,
  },
  // --- Crypto Category ---
  {
    id: 'mock-10',
    title: 'Ethereum\'s Next Frontier: Is Layer 3 the Future of Scalability?',
    slug: 'ethereums-layer-3-future',
    content: '<p>With Layer 2 solutions like Arbitrum and Optimism gaining mainstream adoption, the conversation is already shifting to the next horizon: Layer 3. These application-specific rollups promise hyper-scalability and customization, but also introduce new complexities and potential fragmentation.</p><p>We break down what Layer 3 protocols are, who is building them, and whether they are the key to onboarding the next billion users onto the blockchain or a needless layer of complexity.</p>',
    summary: 'As Layer 2s mature, the crypto world is looking ahead to Layer 3 solutions. We explain what they are, the problems they aim to solve, and the challenges they face.',
    tags: ['Ethereum', 'Layer 3', 'Blockchain', 'Scalability'],
    categories: ['Crypto'],
    company: '',
    imageUrl: 'https://picsum.photos/seed/mock-crypto-1/600/400',
    imageHint: 'abstract blockchain visualization',
    authorId: 'user-2',
    publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    isFeatured: false,
    readTime: 7,
  },
  {
    id: 'mock-11',
    title: 'Bitcoin Halving Aftermath: Miners Adapt to New Economic Reality',
    slug: 'bitcoin-halving-aftermath',
    content: '<p>The recent Bitcoin halving has cut mining rewards in half, forcing miners to innovate or shut down. We analyze the immediate impact on network hashrate, transaction fees, and the strategies miners are employing to stay profitable.</p><p>From investing in more efficient hardware to exploring new revenue streams like Ordinals and Runes, the mining industry is undergoing a period of intense adaptation. This report examines the winners and losers in the post-halving landscape.</p>',
    summary: 'An analysis of the Bitcoin ecosystem following the latest halving event, focusing on how miners are adapting their strategies to remain profitable with reduced block rewards.',
    tags: ['Bitcoin', 'Mining', 'Halving'],
    categories: ['Crypto'],
    company: '',
    imageUrl: 'https://picsum.photos/seed/mock-crypto-2/600/400',
    imageHint: 'server farm mining',
    authorId: 'user-1',
    publishedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    isFeatured: false,
    readTime: 5,
  },
  // --- Startups Category ---
  {
    id: 'mock-20',
    title: 'YC Demo Day Breakdown: Top 5 Startups Tackling Hard Problems',
    slug: 'yc-demo-day-top-5-startups',
    content: '<p>Y Combinator\'s latest batch showcased a clear trend: founders are moving away from SaaS tools and towards deep tech and "hard problems." We profile five standout companies from the W24 batch that are tackling everything from fusion energy to AI-driven protein engineering.</p><p>These startups represent a new wave of ambition in Silicon Valley, attracting significant investor interest despite a tighter funding environment. Here\'s who they are and why they matter.</p>',
    summary: 'Our picks for the most ambitious and promising companies from the latest Y Combinator Demo Day, with a focus on deep tech and challenging industrial problems.',
    tags: ['Y Combinator', 'Startups', 'Venture Capital'],
    categories: ['Startups'],
    company: '',
    imageUrl: 'https://picsum.photos/seed/mock-startup-1/600/400',
    imageHint: 'founder presentation stage',
    authorId: 'user-3',
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    isFeatured: false,
    readTime: 8,
  },
  // --- Tech Category ---
  {
    id: 'mock-30',
    title: 'Apple Vision Pro: One Year Later, Has the Magic Faded?',
    slug: 'apple-vision-pro-one-year-later',
    content: '<p>It launched to immense hype, but a year after its release, has the Apple Vision Pro found its killer app? We speak to developers, early adopters, and industry analysts to gauge the current state of spatial computing.</p><p>While sales have been modest, a dedicated community is pushing the boundaries of the platform. We examine the most compelling use cases, the software ecosystem\'s growth, and what to expect from the inevitable Vision Pro 2.</p>',
    summary: 'A look back at the Apple Vision Pro\'s first year on the market. We assess its impact, the state of its app ecosystem, and whether it has lived up to its revolutionary promise.',
    tags: ['Apple', 'Vision Pro', 'VR', 'AR'],
    categories: ['Tech', 'Big Tech'],
    company: 'comp-2',
    imageUrl: 'https://picsum.photos/seed/mock-tech-1/600/400',
    imageHint: 'person using VR',
    authorId: 'user-2',
    publishedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    isFeatured: false,
    readTime: 6,
  },
  {
    id: 'mock-31',
    title: 'Nvidia\'s Blackwell GPU: A Quantum Leap for AI Infrastructure',
    slug: 'nvidia-blackwell-gpu-quantum-leap',
    content: '<p>Nvidia has unveiled its next-generation GPU architecture, codenamed "Blackwell," and the performance claims are staggering. With a new chiplet design and second-generation transformer engine, the B200 promises an order-of-magnitude leap in training and inference performance for large language models.</p><p>This move solidifies Nvidia\'s dominance in the AI hardware market and sets a new bar for data centers. We break down the architecture, the performance benchmarks, and the implications for the future of AI development.</p>',
    summary: 'Nvidia\'s new Blackwell GPU architecture promises to supercharge the AI industry. We dive into the technical details and what they mean for the future of large-scale AI.',
    tags: ['Nvidia', 'GPU', 'Hardware', 'AI'],
    categories: ['Tech', 'Big Tech', 'AI'],
    company: 'comp-4',
    imageUrl: 'https://picsum.photos/seed/mock-tech-2/600/400',
    imageHint: 'glowing computer chip',
    authorId: 'user-1',
    publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    isFeatured: true,
    readTime: 7,
  },
  // Add more articles to reach 50+
  // ... continue adding articles across categories
  {
    id: 'mock-4',
    title: 'On-Device AI: The Next Privacy Frontier',
    slug: 'on-device-ai-privacy',
    content: '<p>Apple\'s new "Private Cloud Compute" and Google\'s on-device Gemini Nano are signs of a major shift. By processing sensitive data directly on your phone, these systems aim to provide powerful AI features without compromising user privacy. But how secure is it, really? We investigate the technology and the security models behind it.</p>',
    summary: 'Tech giants are moving AI processing from the cloud to your device. We explore how this new paradigm for AI aims to enhance privacy and what the trade-offs are.',
    tags: ['On-Device AI', 'Privacy', 'Apple', 'Google'],
    categories: ['AI', 'Tech', 'Big Tech'],
    company: 'comp-1',
    imageUrl: 'https://picsum.photos/seed/mock-ai-4/600/400',
    imageHint: 'smartphone security lock',
    authorId: 'user-3',
    publishedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    isFeatured: false,
    readTime: 5,
  },
  {
    id: 'mock-12',
    title: 'DeFi Revival? Tokenized Real-World Assets Gain Traction',
    slug: 'defi-revival-rwa',
    content: '<p>After a brutal bear market, Decentralized Finance (DeFi) is finding a new narrative: Real-World Assets (RWAs). Protocols are now tokenizing everything from treasury bonds to private credit, bridging the gap between traditional finance and the blockchain. This could unlock trillions of dollars in liquidity and provide crypto investors with stable, yield-bearing assets. We look at the top projects in the space.</p>',
    summary: 'The tokenization of real-world assets like bonds and real estate is breathing new life into DeFi, offering stable yields and attracting institutional interest.',
    tags: ['DeFi', 'RWA', 'Tokenization', 'Blockchain'],
    categories: ['Crypto'],
    company: '',
    imageUrl: 'https://picsum.photos/seed/mock-crypto-3/600/400',
    imageHint: 'cityscape financial district',
    authorId: 'user-3',
    publishedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    isFeatured: false,
    readTime: 6,
  },
  {
    id: 'mock-21',
    title: 'The AI Co-Pilot for Everything: A New Breed of Startups Emerges',
    slug: 'ai-copilot-startups',
    content: '<p>Forget single-purpose apps. A new wave of startups is building AI "co-pilots" designed to be generalist assistants for knowledge workers. Companies like Adept and Cognition Labs are creating agents that can perform complex, multi-step tasks across different software, heralding a new era of human-computer interaction. But are they ready for prime time?</p>',
    summary: 'Startups are racing to build the ultimate AI agent that can act as a universal co-pilot for your digital life. We examine the technology and the players in this ambitious new field.',
    tags: ['AI Agent', 'Startups', 'Productivity'],
    categories: ['Startups', 'AI'],
    company: '',
    imageUrl: 'https://picsum.photos/seed/mock-startup-2/600/400',
    imageHint: 'futuristic robot assistant',
    authorId: 'user-1',
    publishedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    isFeatured: false,
    readTime: 5,
  },
  {
    id: 'mock-32',
    title: 'The Right to Repair Movement Scores a Major Victory in Oregon',
    slug: 'right-to-repair-oregon',
    content: '<p>Oregon has passed the most comprehensive "Right to Repair" legislation in the United States, mandating that companies like Apple and Google make parts, tools, and schematics available to independent repair shops and consumers. This landmark law could set a precedent for the rest of the country and fundamentally alter the economics of consumer electronics.</p>',
    summary: 'Oregon\'s new Right to Repair law is a huge win for consumers and a potential headache for tech giants, setting a new national standard for device repairability.',
    tags: ['Right to Repair', 'Legislation', 'Apple', 'Consumer Rights'],
    categories: ['Tech', 'Big Tech'],
    company: 'comp-2',
    imageUrl: 'https://picsum.photos/seed/mock-tech-3/600/400',
    imageHint: 'disassembled smartphone tools',
    authorId: 'user-2',
    publishedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    isFeatured: false,
    readTime: 4,
  },
  // Adding more articles...
  {
    id: 'mock-5',
    title: 'AI in Medicine: From Drug Discovery to Diagnostics',
    slug: 'ai-in-medicine',
    content: '<p>Artificial intelligence is making significant inroads in the healthcare sector. AI algorithms are now capable of analyzing medical images with superhuman accuracy, predicting disease outbreaks, and accelerating the discovery of new life-saving drugs. This article reviews the most impactful applications of AI in medicine today.</p>',
    summary: 'Exploring the transformative impact of AI on healthcare, from revolutionizing diagnostic processes to fast-tracking pharmaceutical research and development.',
    tags: ['AI', 'Healthcare', 'Medicine'],
    categories: ['AI', 'Tech'],
    company: 'comp-3',
    imageUrl: 'https://picsum.photos/seed/mock-ai-5/600/400',
    imageHint: 'medical research lab',
    authorId: 'user-1',
    publishedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    isFeatured: false,
    readTime: 6,
  },
  {
    id: 'mock-13',
    title: 'The Rise of Solana: Can it Challenge Ethereum\'s Dominance?',
    slug: 'solana-vs-ethereum',
    content: '<p>Solana has emerged as a major contender in the blockchain space, boasting high transaction speeds and low fees. After overcoming network stability issues, its ecosystem of DeFi and NFT projects is growing rapidly. We analyze its technology and community to see if it has what it takes to unseat Ethereum.</p>',
    summary: 'With its fast transaction speeds and growing ecosystem, Solana is making a serious play for the top spot in the blockchain world. We compare it head-to-head with Ethereum.',
    tags: ['Solana', 'Ethereum', 'Blockchain', 'DeFi'],
    categories: ['Crypto'],
    company: '',
    imageUrl: 'https://picsum.photos/seed/mock-crypto-4/600/400',
    imageHint: 'abstract crypto chart',
    authorId: 'user-2',
    publishedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    isFeatured: false,
    readTime: 5,
  },
  {
    id: 'mock-22',
    title: 'Biotech Startups See Record Funding for Anti-Aging Research',
    slug: 'biotech-anti-aging-funding',
    content: '<p>Venture capitalists are pouring billions into startups focused on extending human lifespan and healthspan. Companies like Altos Labs and Retro Biosciences are using cutting-edge cellular rejuvenation technologies to combat age-related diseases. This article explores the science and the investment frenzy behind the longevity movement.</p>',
    summary: 'The quest for longer, healthier lives is attracting massive investment, with biotech startups pioneering new technologies to reverse the effects of aging.',
    tags: ['Biotech', 'Startups', 'Longevity', 'Funding'],
    categories: ['Startups', 'Tech'],
    company: '',
    imageUrl: 'https://picsum.photos/seed/mock-startup-3/600/400',
    imageHint: 'science lab dna',
    authorId: 'user-3',
    publishedAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    isFeatured: false,
    readTime: 7,
  },
  {
    id: 'mock-33',
    title: 'Custom Silicon: Why Every Tech Giant is Designing Its Own Chips',
    slug: 'custom-silicon-chip-design',
    content: '<p>From Google\'s Tensor to Amazon\'s Graviton, Big Tech is increasingly moving away from off-the-shelf processors from Intel and Qualcomm. By designing their own custom silicon, these companies can optimize performance and efficiency for njihov specific workloads, particularly for AI. This shift is reshaping the semiconductor industry.</p>',
    summary: 'Apple started the trend, and now every major tech company is designing its own chips. We explore the reasons behind the custom silicon push and its impact on the industry.',
    tags: ['Semiconductors', 'Chip Design', 'Apple', 'Google', 'Amazon'],
    categories: ['Tech', 'Big Tech'],
    company: 'comp-4',
    imageUrl: 'https://picsum.photos/seed/mock-tech-4/600/400',
    imageHint: 'silicon wafer circuit',
    authorId: 'user-1',
    publishedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    isFeatured: false,
    readTime: 6,
  },
  {
    id: 'mock-6',
    title: 'Generative Video Models: The Next Frontier in Content Creation',
    slug: 'generative-video-sora',
    content: '<p>OpenAI\'s Sora and Google\'s Veo have demonstrated the incredible potential of text-to-video models. These tools can generate realistic, high-definition video clips from simple text prompts, posing a major disruption to the film and advertising industries. We discuss the technology\'s current limitations and future possibilities.</p>',
    summary: 'Text-to-video AI like OpenAI\'s Sora is set to revolutionize content creation. We examine the current state of the technology and its implications for creative industries.',
    tags: ['Generative AI', 'Video', 'Sora', 'OpenAI'],
    categories: ['AI', 'Tech'],
    company: 'comp-1',
    imageUrl: 'https://picsum.photos/seed/mock-ai-6/600/400',
    imageHint: 'film strip abstract',
    authorId: 'user-2',
    publishedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    isFeatured: false,
    readTime: 5,
  },
  {
    id: 'mock-14',
    title: 'NFTs Are Not Dead: The Evolution into Digital Identity and Assets',
    slug: 'nfts-not-dead-evolution',
    content: '<p>After the 2021 hype cycle, many wrote off NFTs as a fad. However, the underlying technology is finding new, more durable use cases. From token-gated communities and loyalty programs to serving as a form of digital identity, NFTs are quietly becoming a foundational layer of the next-generation internet.</p>',
    summary: 'NFTs are evolving beyond digital art. We explore the new use cases in gaming, digital identity, and loyalty programs that are giving the technology a second life.',
    tags: ['NFT', 'Blockchain', 'Digital Identity'],
    categories: ['Crypto'],
    company: '',
    imageUrl: 'https://picsum.photos/seed/mock-crypto-5/600/400',
    imageHint: 'digital art gallery',
    authorId: 'user-3',
    publishedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    isFeatured: false,
    readTime: 6,
  },
  {
    id: 'mock-23',
    title: 'Nuclear Fusion Startup Raises $200M for Compact Reactor',
    slug: 'nuclear-fusion-startup-funding',
    content: '<p>Helion, a startup focused on nuclear fusion, has secured a massive new funding round to build its next-generation compact reactor. Their unique approach aims to make fusion energy commercially viable within the next decade. We dive into their technology and the ambitious timeline.</p>',
    summary: 'A major funding round for fusion startup Helion signals growing investor confidence that clean, limitless energy from nuclear fusion is within reach.',
    tags: ['Fusion', 'Startups', 'Clean Energy', 'Funding'],
    categories: ['Startups', 'Tech'],
    company: '',
    imageUrl: 'https://picsum.photos/seed/mock-startup-4/600/400',
    imageHint: 'fusion reactor glowing',
    authorId: 'user-1',
    publishedAt: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
    isFeatured: false,
    readTime: 5,
  },
  {
    id: 'mock-34',
    title: 'The Satellite Internet Wars: Starlink vs. Kuiper',
    slug: 'satellite-internet-starlink-kuiper',
    content: '<p>SpaceX\'s Starlink currently dominates the satellite internet market, but Amazon\'s Project Kuiper is poised to become a formidable competitor. With thousands of satellites planned for launch, Amazon is betting big on its ability to provide high-speed internet to underserved areas. This article compares the two mega-constellations.</p>',
    summary: 'It\'s a battle of the billionaires as SpaceX\'s Starlink and Amazon\'s Kuiper compete to dominate the satellite internet market. We compare their strategies and technology.',
    tags: ['Starlink', 'Kuiper', 'Satellite', 'Internet', 'SpaceX', 'Amazon'],
    categories: ['Tech', 'Big Tech'],
    company: 'comp-5',
    imageUrl: 'https://picsum.photos/seed/mock-tech-5/600/400',
    imageHint: 'satellites orbiting earth',
    authorId: 'user-2',
    publishedAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    isFeatured: false,
    readTime: 7,
  },
  {
    id: 'mock-7',
    title: 'The Ethics of AI: Bias, Transparency, and Accountability',
    slug: 'ethics-of-ai',
    content: '<p>As AI systems become more powerful, the ethical challenges they present are becoming more urgent. This article examines the critical issues of algorithmic bias, the need for model transparency, and the question of who is accountable when an AI system makes a harmful decision. We talk to experts who are working to build a more responsible AI framework.</p>',
    summary: 'A deep dive into the pressing ethical questions surrounding AI, including bias, transparency, and how to ensure accountability for AI-driven decisions.',
    tags: ['AI Ethics', 'Bias', 'Accountability'],
    categories: ['AI', 'Society'],
    company: '',
    imageUrl: 'https://picsum.photos/seed/mock-ai-7/600/400',
    imageHint: 'balanced scales justice',
    authorId: 'user-3',
    publishedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    isFeatured: false,
    readTime: 8,
  },
  {
    id: 'mock-15',
    title: 'Web3 Gaming: Still Searching for its Breakout Hit',
    slug: 'web3-gaming-breakout-hit',
    content: '<p>Billions have been invested in Web3 gaming, but a mainstream breakout hit remains elusive. Many early titles prioritized tokenomics over fun, leading to player churn. We look at the next generation of Web3 games that are focusing on gameplay first, and explore whether they can finally bridge the gap to the mass market.</p>',
    summary: 'Despite huge investment, Web3 gaming has yet to produce a killer app. We analyze the mistakes of the first wave and look at the new projects hoping to finally get it right.',
    tags: ['Web3', 'Gaming', 'Blockchain', 'NFT'],
    categories: ['Crypto', 'Gaming'],
    company: '',
    imageUrl: 'https://picsum.photos/seed/mock-crypto-6/600/400',
    imageHint: 'glowing video game controller',
    authorId: 'user-1',
    publishedAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
    isFeatured: false,
    readTime: 6,
  },
  {
    id: 'mock-24',
    title: 'Is the 15-Minute Delivery Dream Dead? Startups Pivot to Survive',
    slug: '15-minute-delivery-pivot',
    content: '<p>The ultra-fast grocery delivery startups that raised billions during the pandemic are now facing a harsh reality. With high cash burn and slim margins, companies like Getir and GoPuff are closing warehouses and laying off staff. We analyze the "deliverpocalypse" and the difficult pivots these companies are making to survive.</p>',
    summary: 'The promise of 15-minute delivery is fading as startups in the space face economic headwinds. We look at the mass layoffs and strategy shifts in the ultra-fast delivery market.',
    tags: ['Startups', 'Delivery', 'Economics'],
    categories: ['Startups'],
    company: '',
    imageUrl: 'https://picsum.photos/seed/mock-startup-5/600/400',
    imageHint: 'delivery scooter city',
    authorId: 'user-2',
    publishedAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    isFeatured: false,
    readTime: 5,
  },
  {
    id: 'mock-35',
    title: 'The Future of Wearables: Beyond the Smartwatch',
    slug: 'future-of-wearables',
    content: '<p>Smartwatches have become commonplace, but the next wave of wearables is far more ambitious. From smart rings that track sleep with incredible accuracy to neural interfaces that promise to read your thoughts, we are on the cusp of a new era of personal computing. This article explores the most innovative devices on the horizon.</p>',
    summary: 'The next generation of wearable technology, including smart rings, AI-powered pins, and neural interfaces, is poised to make the smartwatch look like a relic.',
    tags: ['Wearables', 'Smart Ring', 'Neural Interface', 'Future Tech'],
    categories: ['Tech'],
    company: '',
    imageUrl: 'https://picsum.photos/seed/mock-tech-6/600/400',
    imageHint: 'futuristic smart ring',
    authorId: 'user-3',
    publishedAt: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
    isFeatured: false,
    readTime: 7,
  },
  {
    id: 'mock-8',
    title: 'AI Agents: The Path to Artificial General Intelligence?',
    slug: 'ai-agents-path-to-agi',
    content: '<p>Autonomous AI agents, which can reason, plan, and execute multi-step tasks, are seen by many as a key stepping stone toward Artificial General Intelligence (AGI). We examine the architectures of leading agentic systems like Auto-GPT and BabyAGI, and discuss the immense potential and profound risks they represent.</p>',
    summary: 'Autonomous AI agents can perform complex tasks without human intervention, representing a major leap towards AGI. We explore the technology and its implications.',
    tags: ['AGI', 'AI Agents', 'Autonomous AI'],
    categories: ['AI'],
    company: '',
    imageUrl: 'https://picsum.photos/seed/mock-ai-8/600/400',
    imageHint: 'robot brain thinking',
    authorId: 'user-1',
    publishedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    isFeatured: false,
    readTime: 8,
  },
  {
    id: 'mock-16',
    title: 'Regulatory Crosshairs: How Governments are Approaching Crypto',
    slug: 'crypto-regulation-approach',
    content: '<p>From the SEC\'s lawsuits against exchanges to the EU\'s comprehensive MiCA framework, governments around the world are finally creating clear rules for the cryptocurrency industry. This article provides a global overview of the different regulatory approaches and what they mean for the future of digital assets.</p>',
    summary: 'A comprehensive look at the evolving crypto regulatory landscape in the US, EU, and Asia, and how it\'s shaping the industry\'s future.',
    tags: ['Regulation', 'Crypto', 'SEC', 'Government'],
    categories: ['Crypto', 'Society'],
    company: '',
    imageUrl: 'https://picsum.photos/seed/mock-crypto-7/600/400',
    imageHint: 'government building columns',
    authorId: 'user-2',
    publishedAt: new Date(Date.now() - 32 * 24 * 60 * 60 * 1000).toISOString(),
    isFeatured: false,
    readTime: 7,
  },
  {
    id: 'mock-25',
    title: 'Fintech Startup Disrupts Banking with No-Fee Accounts',
    slug: 'fintech-no-fee-banking',
    content: '<p>A new fintech startup, "Revolt," has launched a checking account with zero monthly fees, no overdraft fees, and a network of free ATMs. By building a lean, all-digital infrastructure, they are directly challenging the business model of traditional banks. Can they achieve profitability at scale?</p>',
    summary: 'New fintech player "Revolt" is making waves by offering a completely free banking experience, putting pressure on incumbent banks to change their fee structures.',
    tags: ['Fintech', 'Banking', 'Startups', 'Disruption'],
    categories: ['Startups', 'Tech'],
    company: '',
    imageUrl: 'https://picsum.photos/seed/mock-startup-6/600/400',
    imageHint: 'digital payment phone',
    authorId: 'user-3',
    publishedAt: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
    isFeatured: false,
    readTime: 5,
  },
  {
    id: 'mock-36',
    title: 'Quantum Computing: When Will it Actually Be Useful?',
    slug: 'quantum-computing-useful',
    content: '<p>The promise of quantum computing is immense, but the timeline for practical applications remains uncertain. We talk to leading researchers at Google, IBM, and startups to separate the hype from reality. This article explains the current state of quantum hardware and identifies the first problems that quantum computers are likely to solve.</p>',
    summary: 'Quantum computing promises to change the world, but when will it move from the lab to real-world applications? We separate the hype from the reality.',
    tags: ['Quantum Computing', 'Future Tech', 'IBM', 'Google'],
    categories: ['Tech', 'Big Tech'],
    company: 'comp-1',
    imageUrl: 'https://picsum.photos/seed/mock-tech-7/600/400',
    imageHint: 'abstract quantum physics',
    authorId: 'user-1',
    publishedAt: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
    isFeatured: false,
    readTime: 9,
  },
  {
    id: 'mock-50',
    title: 'The AI-Powered Job Market: Which Skills Are Now Obsolete?',
    slug: 'ai-job-market-skills',
    content: '<p>As generative AI tools become more integrated into the workplace, the demand for certain skills is rapidly changing. This report analyzes recent job market data to identify the roles most at risk of automation and the new skills that are becoming essential for the AI-augmented workforce.</p>',
    summary: 'Generative AI is transforming the job market. We analyze which skills are losing value and which are becoming more critical in the new AI-powered economy.',
    tags: ['AI', 'Jobs', 'Future of Work'],
    categories: ['AI', 'Society'],
    company: '',
    imageUrl: 'https://picsum.photos/seed/mock-society-1/600/400',
    imageHint: 'office workers modern',
    authorId: 'user-2',
    publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    isFeatured: false,
    readTime: 6,
  },
  {
    id: 'mock-51',
    title: 'Social Media\'s "Enshittification": Can the Cycle Be Broken?',
    slug: 'social-media-enshittification',
    content: '<p>Cory Doctorow\'s theory of "enshittification" describes the inevitable decay of online platforms as they prioritize advertisers and business customers over their users. We examine how this pattern has played out on platforms like Facebook, Twitter (X), and TikTok, and explore the emerging decentralized alternatives that promise a better future.</p>',
    summary: 'From Facebook to TikTok, online platforms seem to follow a predictable cycle of decay. We explore the theory of "enshittification" and the search for a better model.',
    tags: ['Social Media', 'Platform Decay', 'Decentralization'],
    categories: ['Tech', 'Society'],
    company: 'comp-5',
    imageUrl: 'https://picsum.photos/seed/mock-society-2/600/400',
    imageHint: 'scrolling phone social media',
    authorId: 'user-3',
    publishedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    isFeatured: false,
    readTime: 7,
  },
];

// Add more articles to ensure the count is over 50.
const additionalArticles: Partial<Article>[] = [
  { id: 'mock-37', title: 'The Comeback of RSS: A Push for a Decentralized Web', categories: ['Tech', 'Society'], tags: ['RSS', 'Decentralization'] },
  { id: 'mock-38', title: 'Microsoft\'s Big Bet on OpenAI: An Alliance Under Scrutiny', categories: ['Big Tech', 'AI'], tags: ['Microsoft', 'OpenAI'] },
  { id: 'mock-39', title: 'Is WebAssembly the Future of Cloud-Native Computing?', categories: ['Tech'], tags: ['WebAssembly', 'Cloud'] },
  { id: 'mock-40', title: 'The Psychology of Doomscrolling and How to Break the Habit', categories: ['Society'], tags: ['Mental Health', 'Social Media'] },
  { id: 'mock-26', title: 'Climate Tech Startups Attract ESG-Focused Investors', categories: ['Startups', 'Tech'], tags: ['Climate Tech', 'ESG'] },
  { id: 'mock-17', title: 'What Are ZK-Proofs and Why Do They Matter for Privacy?', categories: ['Crypto'], tags: ['ZK-Proofs', 'Privacy'] },
  { id: 'mock-9', title: 'AI-Generated Code: A Programmer\'s Best Friend or Worst Enemy?', categories: ['AI', 'Tech'], tags: ['Copilot', 'Coding', 'AI'] },
  { id: 'mock-41', title: 'The Battle for Your Living Room: Streaming Wars Enter a New Phase', categories: ['Big Tech'], tags: ['Streaming', 'Netflix', 'Disney'] },
  { id: 'mock-42', title: 'E-Waste Crisis: What Happens to Your Old Gadgets?', categories: ['Society', 'Tech'], tags: ['E-Waste', 'Sustainability'] },
  { id: 'mock-27', title: 'The Next Wave of EdTech: Personalized Learning with AI Tutors', categories: ['Startups', 'AI'], tags: ['EdTech', 'AI Tutor'] },
  { id: 'mock-18', title: 'Central Bank Digital Currencies (CBDCs): A Global Status Report', categories: ['Crypto', 'Society'], tags: ['CBDC', 'Finance'] },
  { id: 'mock-43', title: 'The Open-Source Hardware Movement Gains Momentum', categories: ['Tech'], tags: ['RISC-V', 'Open Source', 'Hardware'] },
  { id: 'mock-44', title: 'Gaming\'s Billion-Dollar Acquisitions: Consolidation in the Industry', categories: ['Big Tech', 'Gaming'], tags: ['Gaming', 'Acquisitions', 'Microsoft'] },
  { id: 'mock-28', title: 'Robotics Startup Automates Warehouse Logistics with AI', categories: ['Startups', 'AI'], tags: ['Robotics', 'Logistics'] },
  { id: 'mock-19', title: 'On-Chain Derivatives: The Next Big Thing in DeFi?', categories: ['Crypto'], tags: ['DeFi', 'Derivatives'] },
  { id: 'mock-45', title: 'The Rise of the "Prosumer" and the Creator Economy', categories: ['Society'], tags: ['Creator Economy', 'YouTube'] },
  { id: 'mock-46', title: 'The End of the Smartphone? What Comes Next.', categories: ['Tech'], tags: ['Future Tech', 'AR', 'Wearables'] },
  { id: 'mock-29', title: 'Healthtech Startup Offers At-Home Blood Testing Kits', categories: ['Startups', 'Tech'], tags: ['Healthtech', 'Diagnostics'] },
  { id: 'mock-52', title: 'AI\'s Role in Combating Climate Change', categories: ['AI', 'Society'], tags: ['AI', 'Climate Change'] },
  { id: 'mock-53', title: 'The Digital Divide: How to Bridge the Gap in Internet Access', categories: ['Society'], tags: ['Digital Divide', 'Internet'] },
  { id: 'mock-54', title: 'Regulating Big Tech: A Look at the EU\'s Digital Markets Act', categories: ['Big Tech', 'Society'], tags: ['Regulation', 'DMA', 'EU'] },
  { id: 'mock-55', title: 'The Future of Remote Work: Is Hybrid the Answer?', categories: ['Society'], tags: ['Remote Work', 'Future of Work'] },
  { id: 'mock-56', title: 'Mental Health Apps: Helpful Tool or Privacy Nightmare?', categories: ['Tech', 'Society'], tags: ['Mental Health', 'Privacy'] },
];

let articleCounter = mockArticles.length;
additionalArticles.forEach(article => {
    const randomDate = new Date(Date.now() - (articleCounter * 24 + Math.random() * 20) * 60 * 60 * 1000);
    const fullArticle: Article = {
        id: article.id || `mock-${articleCounter + 1}`,
        title: article.title || 'Placeholder Title',
        slug: article.title ? article.title.toLowerCase().replace(/\s+/g, '-').replace(/[^\w-]+/g, '') : `mock-${articleCounter + 1}`,
        content: `<p>This is a placeholder article about ${article.title}. More content would go here, discussing the nuances and implications of this topic in great detail. The goal is to provide insightful analysis that keeps the reader engaged.</p><p>Further paragraphs would expand on the initial premise, offering data, expert opinions, and future outlooks.</p>`,
        summary: `A summary of the article about "${article.title}". This would typically be a few sentences long.`,
        tags: article.tags || ['Tech'],
        categories: article.categories || ['Tech'],
        company: article.company || '',
        imageUrl: `https://picsum.photos/seed/${article.id || articleCounter}/600/400`,
        imageHint: 'tech abstract',
        authorId: `user-${(articleCounter % 3) + 1}`,
        publishedAt: randomDate.toISOString(),
        isFeatured: false,
        readTime: 4,
    };
    mockArticles.push(fullArticle);
    articleCounter++;
});

    